name-template: Home Assistant OS $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION
version-template: "$MAJOR.$MINOR"
categories:
  - title: 'Home Assistant Operating System'
    label: 'os'
  - title: 'Open Virtual Appliance'
    label: 'board/ova'
filter-by-commitish: true
template: |
  ## Changes

  $CHANGES
version-resolver:
  major:
    labels:
      - 'major'
  default: minor
